#If true, test functions will output data to console when called
GRID_DEBUG_PRINT_FUNCTIONS = False
GRID_SCRIPT_PATH = "..\\Test_Script\\Main_Scripts\\"
GRID_SUBSCRIPT_PATH = "..\\Test_Script\\Subscripts\\"
GRID_SAVED_SCRIPTS_PATH = "..\\Test_Script\\Saved_Scripts\\"
GRID_ARCHIVED_SCRIPTS_PATH = "..\\Test_Script\\Saved_Scripts\\_Archive\\"
GRID_ARCHIVED_MAX = 10 #If we have more than 10, cleanup the directory
GRID_PAN_SPRITE_AMT = 30
GRID_PAN_CAMERA_AMT = 30
#Note that these are the min/max vals allowed to pass in from the tester
#Game_engine logic could cause a +/- 1 for these values if other rules are violated
#eg tile_size should be a multiple of cell_size and may end up <8 to meet this
GRID_WORLD_SIZE_MIN = 40 #px
GRID_WORLD_SIZE_MAX = 5000 #px
GRID_SCREEN_SIZE_MIN = 20 #px
GRID_SCREEN_SIZE_MAX =1600#px
GRID_CELL_SIZE_MIN = 16#px
GRID_CELL_SIZE_MAX = 200#px
GRID_TILE_SIZE_MIN = 8#px
GRID_TILE_SIZE_MAX = 100#px
GRID_HYSTERESIS_MIN = 2#px
GRID_HYSTERESIS_MAX = 200#px
GRID_BEHAVIOR_ID_MIN = 1
GRID_BEHAVIOR_ID_MAX = 3
GRID_RESOURCE_ID_MIN = 0 #When selecting random resource ID's, these are the ranges in use
GRID_RESOURCE_ID_MAX = 0
GRID_LAYERTYPE_MIN = 1
GRID_LAYERTYPE_MAX = 1 #When creating a random layer type, choose from this range
GRID_MAX_TEST_LAYERS = 50 #arbitrary choice for most allowed layers
GRID_MAX_SCENES = 100 #arbitrary choice for most allowed scenes

#printed each loop execution
GRID_TEST_MENU = """\nNext operation: (or -1 to quit):
0)  Exec Statment

1)  Update

2)  Insert Sprite
3)  Remove Sprite

6)  Pan Sprite
7)  Pan Sprite Random
8)  Move Sprite
9)  Move Sprite to Random location

10) Flip Animation

11) Pan Camera
12) Pan Camera Random
13) Move Camera
14) Move Camera Random

15) Load Script

16) Set Current Entity Id (for scripts)
17) Random Current Entity Id (for scripts)

18) Configure Tests (enable or disable them)

19) Set World Size Param (pass in -1 for random set)
20) Set Screen Size Param (pass in -1 for random set)
21) Set Cell Size Param (pass in -1 for random set)
22) Set Hysteresis (pass in -1 for random set)
23) Set Tile Size Param (pass in -1 for random set)
24) Reset Game Engine

25) Load Subscript (run this script then return to the main script)
26) Set number of subscript runthroughs

27) Set Behavior State

30)  Activate Entity
31)  Deactivate Entity
32)  Set Entity Always Active
33)  Remove Entity Always Active
34)  Set Sprite Visible
35)  Set Sprite Invisible
36)  Activate Entity Physics
37)  Deactivate Entity Physics
38)  Activate Entity Behavior
39)  Deactivate Entity Behavior
40)  Activate Entity AI
41)  Deactivate Entity AI

42) Add Entity Dependancy
43) Remove Entity Dependancy
44) Add Dependant
45) Remove Dependant

46) Add Scene
47) Remove Scene 
48) Add Layer
49) Remove Layer
50) Activate Scene
51) Deactivate Scene
52) Add Layer to Current Scene

53) Change script load directory

54) Create Camera
55) Remove Camera
56) Attach Camera
57) Detach Camera
58) Attach Camera to Current

59) Randomized Scene Action

>>>
"""

GRID_CONFIGURE_TEST_MENU = """\nSelect Option:
0) All Testing Disabled
1) All Testing Enabled
>>>
"""

#Testing Choices
GRID_CHOICE_QUIT = -1
GRID_CHOICE_EXEC = 0
GRID_CHOICE_UPDATE = 1
GRID_CHOICE_INSERT_SPRITE = 2
GRID_CHOICE_REMOVE_SPRITE = 3
GRID_CHOICE_PAN_SPRITE = 6
GRID_CHOICE_PAN_SPRITE_RANDOM = 7
GRID_CHOICE_MOVE_SPRITE = 8
GRID_CHOICE_MOVE_SPRITE_RANDOM = 9
GRID_CHOICE_FLIP_ANIMATION = 10
GRID_CHOICE_PAN_CAMERA = 11
GRID_CHOICE_PAN_CAMERA_RANDOM = 12
GRID_CHOICE_MOVE_CAMERA = 13
GRID_CHOICE_MOVE_CAMERA_RANDOM = 14
GRID_CHOICE_LOAD_SCRIPT = 15 #1 argument - the script ID
GRID_CHOICE_SET_ENTITY_ID = 16
GRID_CHOICE_RANDOM_ENTITY_ID = 17
GRID_CHOICE_CONFIGURE_TESTS = 18
GRID_CHOICE_SET_WORLD_SIZE = 19
GRID_CHOICE_SET_SCREEN_SIZE = 20
GRID_CHOICE_SET_CELL_SIZE = 21
GRID_CHOICE_SET_HYSTERESIS = 22
GRID_CHOICE_SET_TILE_SIZE = 23
GRID_CHOICE_RESET_ENGINE = 24
GRID_CHOICE_LOAD_SUBSCRIPT = 25
GRID_CHOICE_SET_SCRIPT_RUNTHROUGHS = 26
GRID_CHOICE_SET_BEHAVIOR_STATE = 27 #-1 for random
GRID_CHOICE_NEW_SEQUENCE = 28

GRID_CHOICE_ACTIVATE_ENTITY = 30
GRID_CHOICE_DEACTIVATE_ENTITY = 31
GRID_CHOICE_SET_ENTITY_ALWAYS_ACTIVE = 32
GRID_CHOICE_REMOVE_ENTITY_ALWAYS_ACTIVE = 33
GRID_CHOICE_SET_SPRITE_VISIBLE = 34
GRID_CHOICE_SET_SPRITE_INVISIBLE = 35
GRID_CHOICE_ACTIVATE_ENTITY_PHYSICS = 36
GRID_CHOICE_DEACTIVATE_ENTITY_PHYSICS = 37
GRID_CHOICE_ACTIVATE_ENTITY_BEHAVIOR = 38
GRID_CHOICE_DEACTIVATE_ENTITY_BEHAVIOR = 39
GRID_CHOICE_ACTIVATE_ENTITY_AI = 40
GRID_CHOICE_DEACTIVATE_ENTITY_AI = 41
GRID_CHOICE_ADD_ENTITY_DEPENDANT = 42
GRID_CHOICE_REMOVE_ENTITY_DEPENDANT = 43
GRID_CHOICE_ADD_DEPENDANT_TO_CURRENT = 44
GRID_CHOICE_RMV_DEPENDANT_FROM_CURRENT = 45

GRID_CHOICE_ADD_SCENE = 46
GRID_CHOICE_REMOVE_SCENE = 47
GRID_CHOICE_ADD_LAYER = 48
GRID_CHOICE_REMOVE_LAYER = 49
GRID_CHOICE_ACTIVATE_SCENE = 50
GRID_CHOICE_DEACTIVATE_SCENE = 51
GRID_CHOICE_ADD_LAYER_TO_CURRENT = 52 #add a random layer to the last created scene

GRID_CHOICE_SET_LOAD_SCRIPT_PATH = 53

GRID_CHOICE_CREATE_CAMERA = 54
GRID_CHOICE_REMOVE_CAMERA = 55
GRID_CHOICE_ATTACH_CAMERA = 56
GRID_CHOICE_DETACH_CAMERA = 57
GRID_CHOICE_ATTACH_CAMERA_TO_CURRENT = 58 #attach last created camera to last created scene


GRID_CHOICE_RANDOM_SCENE_ACTION = 59
GRID_CHOICE_RANDOM_SPRITE_ACTION = 60
GRID_CHOICE_RANDOM_CAMERA_ACTION = 61
GRID_CHOICE_RANDOM_ACTION = 62
GRID_CHOICE_SET_CAMERA_SIZE = 63

GRID_CHOICE_SET_SPRITE_ETHEREAL = 64
GRID_CHOICE_SET_SPRITE_TANGIBLE = 65

GRID_CHOICE_CHAOS = 666

GRID_CHOICE_NOP = 9999

"""
Script a sequence of commands prior to manual input
"""
#Script menu: First index is the menu choice number, second index is the list of args for that action
GRID_SCRIPT_UPDATE = [GRID_CHOICE_UPDATE,[None]]
GRID_SCRIPT_SPRITE_INSERT = [GRID_CHOICE_INSERT_SPRITE,[-1]] #generates a new sprite with random position and state
GRID_SCRIPT_SPRITE_REMOVE = [GRID_CHOICE_REMOVE_SPRITE,[-1]] #use current_entity_id for arg
GRID_SCRIPT_SET_RANDOM_ENTITY = [GRID_CHOICE_RANDOM_ENTITY_ID,[None]]#sets the current_entity_id to a random active one

GRID_SCRIPT_PAN_SPRITE_RANDOM = [GRID_CHOICE_PAN_SPRITE_RANDOM,[-1]]
GRID_SCRIPT_MOVE_SPRITE_ORIGIN = [GRID_CHOICE_MOVE_SPRITE,[-1, [0,0,0]]]
GRID_SCRIPT_MOVE_SPRITE_RANDOM = [GRID_CHOICE_MOVE_SPRITE_RANDOM,[-1]]

GRID_SCRIPT_FLIP_ANIMATION = [GRID_CHOICE_FLIP_ANIMATION, [-1]]
GRID_SCRIPT_SET_BEHAVIOR_RANDOM = [GRID_CHOICE_SET_BEHAVIOR_STATE, [-1,-1]]

GRID_SCRIPT_PAN_CAMERA_RANDOM = [GRID_CHOICE_PAN_CAMERA_RANDOM,[None]]
GRID_SCRIPT_MOVE_CAMERA_ORIGIN = [GRID_CHOICE_MOVE_CAMERA,[[0,0,0]]]
GRID_SCRIPT_MOVE_CAMERA_RANDOM = [GRID_CHOICE_MOVE_CAMERA_RANDOM,[None]]

GRID_SCRIPT_DISABLE_TESTING = [GRID_CHOICE_CONFIGURE_TESTS, [[False, None, None]]]
GRID_SCRIPT_ENABLE_TESTING = [GRID_CHOICE_CONFIGURE_TESTS, [[True, True, True]]]

GRID_SCRIPT_SET_WORLD_SIZE_RANDOM = [GRID_CHOICE_SET_WORLD_SIZE, [-1, -1]]
GRID_SCRIPT_SET_SCREEN_SIZE_RANDOM = [GRID_CHOICE_SET_SCREEN_SIZE, [-1, -1]]
GRID_SCRIPT_SET_CELL_SIZE_RANDOM = [GRID_CHOICE_SET_CELL_SIZE, [-1, -1]]
GRID_SCRIPT_SET_HYSTERESIS_RANDOM = [GRID_CHOICE_SET_HYSTERESIS, [-1, -1, -1, -1]]
GRID_SCRIPT_SET_TILE_SIZE_RANDOM = [GRID_CHOICE_SET_TILE_SIZE, [-1, -1]]
GRID_SCRIPT_RESET_ENGINE = [GRID_CHOICE_RESET_ENGINE, [None]]
GRID_SCRIPT_NEW_SCRIPT_SEQ = [GRID_CHOICE_NEW_SEQUENCE, [None]]

GRID_SCRIPT_ENTITY_ACTIVATE = [GRID_CHOICE_ACTIVATE_ENTITY,[-1]]
GRID_SCRIPT_ENTITY_DEACTIVATE = [GRID_CHOICE_DEACTIVATE_ENTITY,[-1]]

GRID_SCRIPT_ENTITY_AA = [GRID_CHOICE_SET_ENTITY_ALWAYS_ACTIVE,[-1]]
GRID_SCRIPT_ENTITY_NOT_AA = [GRID_CHOICE_REMOVE_ENTITY_ALWAYS_ACTIVE,[-1]]
GRID_SCRIPT_SPRITE_VISIBLE = [GRID_CHOICE_SET_SPRITE_VISIBLE,[-1]]
GRID_SCRIPT_SPRITE_INVISIBLE = [GRID_CHOICE_SET_SPRITE_INVISIBLE,[-1]]

GRID_SCRIPT_SET_SPRITE_ETHEREAL = [GRID_CHOICE_SET_SPRITE_ETHEREAL, [-1]]
GRID_SCRIPT_SET_SPRITE_TANGIBLE = [GRID_CHOICE_SET_SPRITE_TANGIBLE, [-1]]

GRID_SCRIPT_ENTITY_PHYS_ACT= [GRID_CHOICE_ACTIVATE_ENTITY_PHYSICS,[-1]]
GRID_SCRIPT_ENTITY_PHYS_DEACT = [GRID_CHOICE_DEACTIVATE_ENTITY_PHYSICS,[-1]]
GRID_SCRIPT_ENTITY_BEH_ACT = [GRID_CHOICE_ACTIVATE_ENTITY_BEHAVIOR,[-1]]
GRID_SCRIPT_ENTITY_BEH_DEACT = [GRID_CHOICE_DEACTIVATE_ENTITY_BEHAVIOR,[-1]]
GRID_SCRIPT_ENTITY_AI_ACT = [GRID_CHOICE_ACTIVATE_ENTITY_AI,[-1]]
GRID_SCRIPT_ENTITY_AI_DEACT = [GRID_CHOICE_DEACTIVATE_ENTITY_AI,[-1]]
GRID_SCRIPT_ENTITY_ADD_DEP = [GRID_CHOICE_ADD_ENTITY_DEPENDANT,[-1, -1]] #add random entity dependancy if possible
GRID_SCRIPT_ENTITY_REMOVE_DEP = [GRID_CHOICE_REMOVE_ENTITY_DEPENDANT,[-1, -1]] #remove random entity dependancy
GRID_SCRIPT_ENTITY_ADD_CURENT = [GRID_CHOICE_ADD_DEPENDANT_TO_CURRENT, [None]]
GRID_SCRIPT_ENTITY_RMV_CURENT = [GRID_CHOICE_RMV_DEPENDANT_FROM_CURRENT, [None]]

GRID_SCRIPT_ADD_SCENE = [GRID_CHOICE_ADD_SCENE, [-1,-1,-1]]
GRID_SCRIPT_REMOVE_SCENE = [GRID_CHOICE_REMOVE_SCENE, [-1]] #-1 for remove a random scene
GRID_SCRIPT_ADD_LAYER = [GRID_CHOICE_ADD_LAYER, [-1]] #-1 for random,
GRID_SCRIPT_REMOVE_LAYER = [GRID_CHOICE_REMOVE_LAYER, [-1]] #-1 for random
GRID_SCRIPT_ADD_LAYER_TO_CURRENT = [GRID_CHOICE_ADD_LAYER_TO_CURRENT, [-1]]

GRID_SCRIPT_ACTIVATE_SCENE = [GRID_CHOICE_ACTIVATE_SCENE, [-1]]
GRID_SCRIPT_DEACTIVATE_SCENE = [GRID_CHOICE_DEACTIVATE_SCENE, [-1]]

GRID_SCRIPT_CREATE_CAMERA = [GRID_CHOICE_CREATE_CAMERA, [-1, -1, -1]]
GRID_SCRIPT_REMOVE_CAMERA = [GRID_CHOICE_REMOVE_CAMERA, [-1]]
GRID_SCRIPT_ATTACH_CAMERA = [GRID_CHOICE_ATTACH_CAMERA, [-1,-1,-1]] #scene_id, camera_id, position
GRID_SCRIPT_DETACH_CAMERA = [GRID_CHOICE_DETACH_CAMERA, [-1]] #camera_id
GRID_SCRIPT_ATTACH_CAMERA_TO_CURRENT = [GRID_CHOICE_ATTACH_CAMERA_TO_CURRENT, [None]]
GRID_SCRIPT_SET_CAMERA_SIZE = [GRID_CHOICE_SET_CAMERA_SIZE, [-1, -1]] #camera_id, window_size
GRID_SCRIPT_RANDOM_SCENE_ACTION = [GRID_CHOICE_RANDOM_SCENE_ACTION, [None]]
GRID_SCRIPT_RANDOM_SPRITE_ACTION = [GRID_CHOICE_RANDOM_SPRITE_ACTION, [None]]
GRID_SCRIPT_RANDOM_CAMERA_ACTION = [GRID_CHOICE_RANDOM_CAMERA_ACTION, [None]]
GRID_SCRIPT_RANDOM_ACTION = [GRID_CHOICE_RANDOM_ACTION, [None]]
#Shortcuts that can be used for JSON scripts (or hardcoded scripts) - these JSON strings map to the defined lists
GRID_SCRIPT_MAP = {
'update':GRID_SCRIPT_UPDATE,
'sprite_insert': GRID_SCRIPT_SPRITE_INSERT,
'sprite_remove': GRID_SCRIPT_SPRITE_REMOVE,
'pan_sprite_random': GRID_SCRIPT_PAN_SPRITE_RANDOM,
'move_sprite_origin': GRID_SCRIPT_MOVE_SPRITE_ORIGIN,
'move_sprite_random' : GRID_SCRIPT_MOVE_SPRITE_RANDOM,
'flip_animation' : GRID_SCRIPT_FLIP_ANIMATION,
'random_behavior_state' : GRID_SCRIPT_SET_BEHAVIOR_RANDOM,
'pan_camera_random' : GRID_SCRIPT_PAN_CAMERA_RANDOM,
'move_camera_origin' : GRID_SCRIPT_MOVE_CAMERA_ORIGIN,
'move_camera_random' : GRID_SCRIPT_MOVE_CAMERA_RANDOM,
'disable_testing' : GRID_SCRIPT_DISABLE_TESTING,
'enable_testing' : GRID_SCRIPT_ENABLE_TESTING,
'set_random_entity' : GRID_SCRIPT_SET_RANDOM_ENTITY,
'set_random_world_size' : GRID_SCRIPT_SET_WORLD_SIZE_RANDOM,
'set_random_screen_size' : GRID_SCRIPT_SET_SCREEN_SIZE_RANDOM,
'set_random_cell_size' : GRID_SCRIPT_SET_CELL_SIZE_RANDOM,
'set_random_hysteresis' : GRID_SCRIPT_SET_HYSTERESIS_RANDOM,
'set_random_tile_size' : GRID_SCRIPT_SET_TILE_SIZE_RANDOM,
'reset_engine' : GRID_SCRIPT_RESET_ENGINE,
'entity_activate': GRID_SCRIPT_ENTITY_ACTIVATE,
'entity_deactive': GRID_SCRIPT_ENTITY_DEACTIVATE,
'entity_always_active': GRID_SCRIPT_ENTITY_AA,
'entity_not_always_active': GRID_SCRIPT_ENTITY_NOT_AA,
'sprite_visible': GRID_SCRIPT_SPRITE_VISIBLE,
'sprite_invisible': GRID_SCRIPT_SPRITE_INVISIBLE,
'sprite_ethereal' : GRID_SCRIPT_SET_SPRITE_ETHEREAL,
'sprite_tangible' : GRID_SCRIPT_SET_SPRITE_TANGIBLE,
'entity_phys_active': GRID_SCRIPT_ENTITY_PHYS_ACT,
'entity_phys_inactive': GRID_SCRIPT_ENTITY_PHYS_DEACT,
'entity_beh_active': GRID_SCRIPT_ENTITY_BEH_ACT,
'entity_beh_inactive': GRID_SCRIPT_ENTITY_BEH_DEACT,
'entity_ai_active': GRID_SCRIPT_ENTITY_AI_ACT,
'entity_ai_deactive': GRID_SCRIPT_ENTITY_AI_DEACT,
'entity_add_random_depend': GRID_SCRIPT_ENTITY_ADD_DEP,
'entity_add_current_depend': GRID_SCRIPT_ENTITY_ADD_CURENT,
'entity_remove_random_depend': GRID_SCRIPT_ENTITY_REMOVE_DEP,
'entity_remove_current_depend': GRID_SCRIPT_ENTITY_RMV_CURENT,
'start_new_script_sequence': GRID_SCRIPT_NEW_SCRIPT_SEQ,
'add_new_scene': GRID_SCRIPT_ADD_SCENE,
'remove_random_scene': GRID_SCRIPT_REMOVE_SCENE,
'add_random_layer': GRID_SCRIPT_ADD_LAYER,
'remove_random_layer': GRID_SCRIPT_REMOVE_LAYER,
'activate_random_scene' : GRID_SCRIPT_ACTIVATE_SCENE,
'deactivate_random_scene' : GRID_SCRIPT_DEACTIVATE_SCENE,
'add_layer_to_current' : GRID_SCRIPT_ADD_LAYER_TO_CURRENT,
'create_camera' : GRID_SCRIPT_CREATE_CAMERA,
'remove_camera' : GRID_SCRIPT_REMOVE_CAMERA,
'attach_camera' : GRID_SCRIPT_ATTACH_CAMERA,
'detach_camera' : GRID_SCRIPT_DETACH_CAMERA,
'attach_camera_current' : GRID_SCRIPT_ATTACH_CAMERA_TO_CURRENT,
'set_camera_size' : GRID_SCRIPT_SET_CAMERA_SIZE,
'random_scene_action' : GRID_SCRIPT_RANDOM_SCENE_ACTION,
'random_sprite_action' : GRID_SCRIPT_RANDOM_SPRITE_ACTION,
'random_camera_action' : GRID_SCRIPT_RANDOM_CAMERA_ACTION,
'random_action' : GRID_SCRIPT_RANDOM_ACTION,
}

#Purely because of my stupid decision to use ints, and needing a more readible console output
CHOICE_STRING_MAP ={
-1 : "QUIT",
0 : "EXEC",
1 : "UPDATE",
2 : "INSERT_SPRITE",
3 : "REMOVE_SPRITE",
6 : "PAN_SPRITE",
7 : "PAN_SPRITE_RANDOM",
8 : "MOVE_SPRITE",
9 : "MOVE_SPRITE_RANDOM",
10 : "FLIP_ANIMATION",
11 : "PAN_CAMERA",
12 : "PAN_CAMERA_RANDOM",
13 : "MOVE_CAMERA",
14 : "MOVE_CAMERA_RANDOM",
15 : "LOAD_SCRIPT",
16 : "SET_ENTITY_ID",
17 : "RANDOM_ENTITY_ID",
18 : "CONFIGURE_TESTS",
19 : "SET_WORLD_SIZE",
20 : "SET_SCREEN_SIZE",
21 : "SET_CELL_SIZE",
22 : "SET_HYSTERESIS",
23 : "SET_TILE_SIZE",
24 : "RESET_ENGINE",
25 : "LOAD_SUBSCRIPT",
26 : "SET_SCRIPT_RUNTHROUGHS",
27 : "SET_BEHAVIOR_STATE",
28 : "NEW_SCRIPT_SEQ",
30 : "ACTIVATE_ENTITY",
31 : "DEACTIVATE_ENTITY",
32 : "SET_ENTITY_ALWAYS_ACTIVE",
33 : "REMOVE_ENTITY_ALWAYS_ACTIVE",
34 : "SET_SPRITE_VISIBLE",
35 : "SET_SPRITE_INVISIBLE",
36 : "ACTIVATE_ENTITY_PHYSICS",
37 : "DEACTIVATE_ENTITY_PHYSICS",
38 : "ACTIVATE_ENTITY_BEHAVIOR",
39 : "DEACTIVATE_ENTITY_BEHAVIOR",
40 : "ACTIVATE_ENTITY_AI",
41 : "DEACTIVATE_ENTITY_AI",
42 : "ADD_ENTITY_DEPENDANT",
43 : "REMOVE_ENTITY_DEPENDANT",
44 : "ADD_ENTITY_DEPENDANT",
45 : "REMOVE_ENTITY_DEPENDANT",
46 : "ADD_SCENE",
47 : "REMOVE_SCENE",
48 : "ADD_LAYER",
49 : "REMOVE_LAYER",
50 : "ACTIVATE_SCENE",
51 : "DEACTIVATE_SCENE",
52 :  "ADD LAYER TO CURRENT",
53 : "CHANGE SCRIPT PATH",
54 : "CREATE_CAMERA",
55 : "REMOVE_CAMERA",
56 : "ATTACH_CAMERA",
57 : "DETACH_CAMERA",
58 : "ATTACH_CAMERA_TO_CURRENT",
59 : "RANDOM_SCENE_ACTION",
60 : "RANDOM_SPRITE_ACTION",
61 : "RANDOM_CAMERA_ACTION",
62 : "RANDOM_ACTION",
63 : "SET CAMERA SIZE",
64 : "SPRITE ETHEREAL",
65 : "SPRITE TANGIBLE",
9999 : "NOP",
}
